### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by lilialnas** [LucasFelinto/ifparking#1]
- [x] Definição do framework = Laravel e configuração
- [x] Criação do modelo de dados
- [x] Read.me com conteúdo do projeto
- [x] Criação do arquivo makefile (todos os users do git de vocês no projeto)
