### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by lilialnas** [LucasFelinto/ifparking#18]
- [ ] Criação do autocadastro do usuário
- [ ] Cadastro do veículo
- [ ] Cadastro do estacionamento (módulo do administrador) 
OBS: Somente usuário administrador pode cadastrar. O banco tá preparado para ter um administrador do sistema?
