### ISSUE TITLE
Sprint 4

### ISSUE THREAD

**Issue by lilialnas** [LucasFelinto/ifparking#23]
- [ ] Criação do autocadastro do usuário (retrabalho da sprint 3)
- [ ] Cadastro do veículo  (retrabalho da sprint 3)
- [ ] Cadastro do estacionamento (módulo do administrador)  (retrabalho da sprint 3)
OBS: Somente usuário administrador pode cadastrar. O banco tá preparado para ter um administrador do sistema? 
- [ ] Alocação de vaga
- [ ] Registro de vaga

**Comment by ricardomlp** [comment]
Compartilho vídeo com exemplo demonstrativo de um estacionamento virtual:
https://youtu.be/XKsj8KTLn34
