### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by lilialnas** [LucasFelinto/ifparking#6]
- [x] Criação do modelo de dados (retrabalho Sprint 1)
- [x] Criação dos models e seeds para models
- [x] Criação de página inicial

**Comment by Patrick-Santana** [comment]
![Modelo](https://user-images.githubusercontent.com/48485663/93939021-89167880-fd00-11ea-801f-5f30bb70eb31.png)


- Modelo Pretendido
